/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET SQL_NOTES=0 */;
DROP TABLE IF EXISTS accidents;
CREATE TABLE `accidents` (
  `id` int NOT NULL AUTO_INCREMENT,
  `create_time` datetime DEFAULT NULL COMMENT 'create time',
  `update_time` datetime DEFAULT NULL COMMENT 'update time',
  `SiglaEmpresa` varchar(7) NOT NULL,
  `SiglaSede` varchar(7) NOT NULL,
  `NombreEmpresa` varchar(255) DEFAULT NULL,
  `TipoIdentificacion` varchar(20) DEFAULT NULL,
  `Identificacion` int NOT NULL,
  `Genero` varchar(20) NOT NULL,
  `Nombre` varchar(255) NOT NULL,
  `TipoContrato` varchar(50) NOT NULL,
  `FechaAT` date NOT NULL,
  `HoraAT` time NOT NULL,
  `AreaTrabajo` varchar(255) DEFAULT NULL,
  `NombreAreaTrabajo` varchar(255) DEFAULT NULL,
  `OficioHabitual` varchar(255) DEFAULT NULL,
  `TareaAT` varchar(255) DEFAULT NULL,
  `DiasIncapacidad` int DEFAULT NULL,
  `ParteCuerpo` varchar(255) DEFAULT NULL,
  `NaturalezaLesion` varchar(255) DEFAULT NULL,
  `AgenteLesion` varchar(255) DEFAULT NULL,
  `TipoAT` varchar(255) DEFAULT NULL,
  `Peligro` varchar(255) DEFAULT NULL,
  `OrigenAT` varchar(255) DEFAULT NULL,
  `CausaAT` varchar(255) DEFAULT NULL,
  `ATgrave` varchar(255) DEFAULT NULL,
  `FechaReporteARL` date DEFAULT NULL,
  `DescripcionAT` text,
  `Observaciones` text,
  `ATInvestigado` varchar(255) DEFAULT NULL,
  `PlanPropuesto` int DEFAULT NULL,
  `PlanEjecutado` int DEFAULT NULL,
  `CierrePlan` varchar(255) DEFAULT NULL,
  `Furat` varchar(255) DEFAULT NULL,
  `FormatoInvestigacion` varchar(255) DEFAULT NULL,
  `VersionAccidentado` varchar(255) DEFAULT NULL,
  `VersionTestigos` varchar(255) DEFAULT NULL,
  `AnalisisCausa` varchar(255) DEFAULT NULL,
  `EvidenciaFotografica` varchar(255) DEFAULT NULL,
  `LeccionAprendida` varchar(255) DEFAULT NULL,
  `DivulgacionLeccionAprendida` varchar(255) DEFAULT NULL,
  `user_id` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_user` (`user_id`),
  CONSTRAINT `fk_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb3 COMMENT='primary key';